### ISSUE TITLE
Debian oracle-java installation no longer works

### ISSUE THREAD

**Issue by pongsatorn-srw** [opsta/ansible-java#3]
FYI
I pulled your repository for working and find out this problem.

According to this information.
https://launchpad.net/~webupd8team/+archive/ubuntu/java
It said webupd8team has discontinued the PPA for Oracle JDK 8 due to newly updated license from Oracle. 

If you find another way round to install jdk for debian-based linux, please update. 
Noted with thanks.

**Comment by winggundamth** [comment]
We move to use openjdk instead while no work around for oracle jdk. thanks for reporting.
